version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
    - make setup
    - make test
reports:
  unittest:
    files: 
      - report.xml
    file-format: "JUNITXML"
  codecoverage:
    files:
      - coverage.xml
    file-format: COBERTURAXML